<?php

namespace Spatie\WebhookServer\Tests;

use Orchestra\Testbench\TestCase as Orchestra;
use Spatie\WebhookServer\WebhookServerServiceProvider;

class TestCase extends Orchestra
{
    public function setUp(): void
    {
        die('setting up');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
            WebhookServerServiceProvider::class,
        ];
    }
}

